Repository Kirakira-Games/BanGround-Unity, pull requests merged in 2021-09, with the labels that each got.

#154 Check update using remote KVars
  Assets/Codes/Injector/GlobalInstaller.cs
  Assets/Codes/KVar/IKVSystem.cs
  Assets/Codes/KVar/KVar.cs
  Assets/Codes/Title/TitleLoader.cs
  Assets/Codes/Title/TouchEvent.cs
  Assets/Codes/Web/Profile.cs
  Assets/Codes/Web/Profile.cs.meta
  Assets/Codes/Web/VersionCheck.cs
  Packages/manifest.json
  Packages/packages-lock.json
Labels: enhancement

#155 Fix #136
  Assets/Codes/InGame/Controllers/NoteController.cs
  Assets/Codes/Injector/GlobalInstaller.cs
  Assets/Codes/Select/SettingPanel.cs
  Assets/LanguageFiles/english.txt
  Assets/LanguageFiles/schinese.txt
  Assets/Scenes/Select.unity
Labels: enhancement

#159 Release 0.10.2 (4)
  Assets/Codes/KVar/KVar.cs
  Assets/Codes/Title/TitleLoader.cs
  ProjectSettings/ProjectSettings.asset
Labels: release

#167 Fix #162, #164, #165, #166
  Assets/Codes/InGame/Controllers/UIManager.cs
  Assets/Codes/InGame/Input/DemoReplayTouchProvider.cs
  Assets/Codes/InGame/Input/TouchManager.cs
  Assets/Codes/Injector/InGameInstaller.cs
  Assets/LanguageFiles/english.txt
  Assets/LanguageFiles/mars.txt
  Assets/LanguageFiles/schinese.txt
  Assets/Resources/Prefab/RankTable.prefab
  Assets/Resources/Prefab/Slide.prefab
  Assets/Scenes/Select.unity
  Assets/Scenes/Title.unity
Labels: P1

#168 Release 0.10.2 (6)
  Assets/Codes/InGame/Controllers/UIManager.cs
  Assets/Codes/InGame/Input/DemoReplayTouchProvider.cs
  Assets/Codes/InGame/Input/TouchManager.cs
  Assets/Codes/Injector/InGameInstaller.cs
  Assets/Codes/Result/ELDisplayDetail.cs
  Assets/LanguageFiles/english.txt
  Assets/LanguageFiles/mars.txt
  Assets/LanguageFiles/schinese.txt
  Assets/Resources/Prefab/RankTable.prefab
  Assets/Resources/Prefab/Slide.prefab
  Assets/Scenes/Select.unity
  Assets/Scenes/Title.unity
  ProjectSettings/ProjectSettings.asset
Labels: release

#170 Release 0.10.2 (7)
  Assets/Codes/InGame/Controllers/NotePool.cs
  Assets/Codes/InGame/Notes/NoteBase.cs
  Assets/Codes/InGame/Notes/Slide.cs
  Assets/Codes/InGame/Notes/SlideStart.cs
  ProjectSettings/ProjectSettings.asset
Labels: release
